# Generated by Django 5.2 on 2025-05-09 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_alter_measurementdevice_calibration_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_type', models.CharField(choices=[('verification', 'Поверка'), ('calibration', 'Калибровка'), ('control', 'Контроль')], max_length=25, verbose_name='Вид работы')),
                ('calibration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поверки')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей поверки')),
                ('calibration_result', models.CharField(choices=[('passed', 'Годен'), ('failed', 'Не годен')], default='passed', max_length=255)),
                ('calibration_certificate_number', models.CharField(max_length=35, verbose_name='Номер свидетельства')),
                ('calibration_certificate_file', models.FileField(blank=True, null=True, upload_to='calibration_certificates/')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_events', to='devices.measurementdevice')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_by', to='calibrations.organization')),
            ],
            options={
                'verbose_name': 'Проведение поверки/калибровки',
                'verbose_name_plural': 'Проведения поверки/калибровки',
                'ordering': ['-calibration_date'],
            },
        ),
    ]
