# Generated by Django 5.2 on 2025-04-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('device_type', models.CharField(choices=[('pressure', 'Манометр'), ('temperature', 'Термометр'), ('weight', 'Весы'), ('voltage', 'Вольтметр'), ('current', 'Амперметр'), ('frequency', 'Частотомер'), ('resistance', 'Омметр'), ('lenght', 'Линейка'), ('lenght_micrometer', 'Микрометр'), ('lenght_vernier', 'Нутромер'), ('lenght_vernier_caliper', 'Штангенциркуль'), ('other', 'Другое')], max_length=255, verbose_name='Тип средства измерения')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('manufacturer', models.CharField(default=None, max_length=255, null=True, verbose_name='Производитель')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='Дата поверки')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей поверки')),
                ('calibration_interval', models.IntegerField(blank=True, null=True, verbose_name='Периодичность поверки')),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер свидетельства')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Свидетельство')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.department')),
            ],
        ),
    ]
