# Generated by Django 5.2 on 2025-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdevice',
            name='device_type',
            field=models.CharField(max_length=255, verbose_name='Тип средства измерения'),
        ),
        migrations.AlterField(
            model_name='measurementdevice',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='measurementdevice',
            name='name',
            field=models.CharField(choices=[('pressure', 'Манометр'), ('temperature', 'Термометр'), ('weight', 'Весы'), ('voltage', 'Вольтметр'), ('current', 'Амперметр'), ('frequency', 'Частотомер'), ('resistance', 'Омметр'), ('lenght', 'Линейка'), ('lenght_micrometer', 'Микрометр'), ('lenght_vernier', 'Нутромер'), ('lenght_vernier_caliper', 'Штангенциркуль'), ('other', 'Другое')], max_length=255, verbose_name='Наименование'),
        ),
    ]
