# Generated by Django 5.2 on 2025-05-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdevice',
            name='calibration_interval',
            field=models.IntegerField(default=12, verbose_name='Периодичность поверки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurementdevice',
            name='owner_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.department', verbose_name='Подразделение'),
        ),
    ]
