# Generated by Django 5.2 on 2025-04-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_measurementdevice_device_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdevice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='measurementdevice',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
