# Generated by Django 5.2 on 2025-04-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_measurementdevice_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdevice',
            name='status',
            field=models.CharField(choices=[('valid', 'Действующий'), ('overdue', 'Просрочен'), ('storage', 'Хранение')], default='active', max_length=255, verbose_name='Статус'),
        ),
    ]
