# Generated by Django 5.2 on 2025-05-01 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('storekeeper', 'Кладовщик'), ('metrologist', 'Метролог'), ('admin', 'Администратор'), ('engineer', 'Инженер'), ('worker', 'Работник')], default='worker', max_length=255, verbose_name='Роль')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
